export type ComponentCategory =
  | "auth"
  | "marketing"
  | "data"
  | "commerce"
  | "files"
  | "content"
  | "api"
  | "forms"
  | "hero"
  | "saas"
  | "ui"
  | "home"
  | "shared"
  | "chat"
  | "profile";

export type ComponentSource =
  | "JB"
  | "21st.dev"
  | "shadcnblocks"
  | "shadcn-space"
  | "ncdai"
  | "magicui"
  | "external";

export type JBComponent = {
  slug: string;
  name: string;
  tagline: string;
  category: ComponentCategory;
  categoryLabel: string;
  install: string;
  blogUrl?: string;
  source?: ComponentSource;
  sourceLabel?: string;
  prerequisites?: string[];
  envVars?: { name: string; description: string }[];
  features: string[];
  whenToUse: string;
  whenNotToUse: string;
  filesAdded?: string[];
  registryDependencies?: string[];
};

export const components: JBComponent[] = [
  // ─── UI Primitives ─────────────────────────
  {
    slug: "button",
    name: "Button",
    tagline: "Dark-only pressable button with primary, secondary, ghost, destructive, and text variants. Loading spinner, icons via Ionicons, and full-width support.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install button",
    features: [
      "5 variants: primary, secondary, ghost, destructive, text",
      "3 sizes: sm, md, lg with responsive hit areas",
      "Loading state with ActivityIndicator spinner",
      "Leading and trailing icon support via @expo/vector-icons (Ionicons)",
      "Full-width mode with stretch alignment",
      "Disabled state with reduced opacity",
    ],
    whenToUse: "Any touchable action — form submission, navigation CTAs, modal triggers, list item actions.",
    whenNotToUse: "Inline text interactions (use a plain Pressable or a text-only variant).",
    filesAdded: ["components/ui/button.tsx"],
  },
  {
    slug: "input",
    name: "Input",
    tagline: "Dark-only text input with label, error, leading icon, and password visibility toggle.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install input",
    features: [
      "Label, error message, and helper text support",
      "Leading icon via Ionicons",
      "Password visibility toggle for secure fields",
      "Dark-only styling with indigo focus ring",
      "Disabled state",
    ],
    whenToUse: "Forms, search fields, authentication screens, any text entry point.",
    whenNotToUse: "Multi-line text entry (use TextInput with multiline directly), or OTP input (use otp-input component).",
    filesAdded: ["components/ui/input.tsx"],
  },
  {
    slug: "badge",
    name: "Badge",
    tagline: "Compact status badge with solid, outline, and subtle variants for tags, counts, and labels.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install badge",
    features: [
      "3 variants: solid, outline, subtle",
      "Small compact size for inline display",
      "Custom text and background colors via props",
    ],
    whenToUse: "Status indicators, notification counts, tag labels, discount badges on product cards.",
    whenNotToUse: "Interactive elements (use a Pressable with badge styling).",
    filesAdded: ["components/ui/badge.tsx"],
  },
  {
    slug: "avatar",
    name: "Avatar",
    tagline: "Circular avatar with image, fallback initials, and online status dot.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install avatar",
    features: [
      "Image avatar with expo-image caching",
      "Initials fallback when no image provided",
      "Online/offline status dot indicator",
      "Configurable size",
    ],
    whenToUse: "User profile pictures, comment threads, member lists, chat headers.",
    whenNotToUse: "Product images (use a Card or Image component instead).",
    filesAdded: ["components/ui/avatar.tsx"],
  },
  {
    slug: "card",
    name: "Card",
    tagline: "Elevated dark card container with optional header, body, and footer sections.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install card",
    features: [
      "Elevated dark surface with rounded corners",
      "Optional header, body, and footer sections",
      "Custom padding configuration",
    ],
    whenToUse: "Grouping related content — product cards, settings sections, information panels.",
    whenNotToUse: "Simple containers without elevation (use a plain View instead).",
    filesAdded: ["components/ui/card.tsx"],
  },
  {
    slug: "bottom-sheet",
    name: "Bottom Sheet",
    tagline: "Modal bottom sheet with backdrop, drag handle, snap points, and smooth open/close animation.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install bottom-sheet",
    features: [
      "Animated open/close with spring physics",
      "Backdrop overlay with press-to-dismiss",
      "Visual drag handle at top",
      "Custom content area with scroll support",
    ],
    whenToUse: "Mobile-native modals — action sheets, filter panels, option pickers, share sheets.",
    whenNotToUse: "Full-screen forms or dialogs (use a modal or stack navigation instead).",
    filesAdded: ["components/ui/bottom-sheet.tsx"],
  },
  {
    slug: "empty-state",
    name: "Empty State",
    tagline: "Empty state with icon, title, message, and optional action button for zero-data screens.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install empty-state",
    features: [
      "Custom icon via Ionicons or node",
      "Title, subtitle, and description text",
      "Optional action button for guided recovery",
    ],
    whenToUse: "Empty lists, no search results, onboarding states, error recovery screens.",
    whenNotToUse: "Loading state (use loading-spinner or skeleton instead).",
    filesAdded: ["components/ui/empty-state.tsx"],
  },
  {
    slug: "loading-spinner",
    name: "Loading Spinner",
    tagline: "Full-screen or inline loading spinner with ActivityIndicator and optional overlay message.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install loading-spinner",
    features: [
      "Full-screen overlay mode with backdrop",
      "Inline mode for embedded use",
      "Configurable color and size",
      "Optional loading message below spinner",
    ],
    whenToUse: "Page loads, form submissions, API calls, any async operation.",
    whenNotToUse: "Content skeletons (use skeleton component for card/list placeholders).",
    filesAdded: ["components/ui/loading-spinner.tsx"],
  },
  {
    slug: "toast",
    name: "Toast",
    tagline: "Animated toast notifications with success, error, warning, and info variants.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install toast",
    features: [
      "4 variants: success, error, warning, info with matching colors",
      "Slide-in animation from top with spring physics",
      "Auto-dismiss with configurable duration",
      "Icon per variant via Ionicons",
      "Singleton hook-based API (useToast)",
    ],
    whenToUse: "Transient feedback — form submission success, error messages, status updates.",
    whenNotToUse: "Persistent messages or critical alerts (use a modal or banner instead).",
    filesAdded: ["components/ui/toast.tsx"],
  },
  {
    slug: "rating",
    name: "Rating",
    tagline: "Interactive star rating with half-star precision, touch selection, and display-only mode.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install rating",
    features: [
      "Interactive star selection with touch feedback",
      "Display-only mode for reviews",
      "Configurable max stars and size",
      "Semi-star support for fractional ratings",
    ],
    whenToUse: "Product reviews, service ratings, feedback forms, review display.",
    whenNotToUse: "Binary thumbs up/down (use a simple icon toggle instead).",
    filesAdded: ["components/ui/rating.tsx"],
  },
  {
    slug: "custom-radio",
    name: "Custom Radio",
    tagline: "Styled radio button group with animated selection indicator and vertical/horizontal layout.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install custom-radio",
    features: [
      "Vertical and horizontal layout modes",
      "Animated selection indicator",
      "Label and description per option",
      "Disabled individual options",
    ],
    whenToUse: "Single-select lists — payment method selection, option pickers, survey questions.",
    whenNotToUse: "Multi-select lists (use checkboxes or custom-radio with multiple mode).",
    filesAdded: ["components/ui/custom-radio.tsx"],
  },
  {
    slug: "divider",
    name: "Divider",
    tagline: "Thin horizontal or vertical divider line with optional label inset.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install divider",
    features: [
      "Horizontal and vertical orientation",
      "Optional centered label with line inset",
      "Custom color",
    ],
    whenToUse: "Section separation in forms, lists, settings pages, content sections.",
    whenNotToUse: "Whitespace-based separation (use margin/padding instead).",
    filesAdded: ["components/ui/divider.tsx"],
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    tagline: "Pulsing placeholder shapes for card, text, avatar, and custom layouts during loading.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install skeleton",
    features: [
      "Pre-built variants: card, text, avatar, circle",
      "Pulsing opacity animation",
      "Custom dimensions via props",
      "Composable for custom skeleton layouts",
    ],
    whenToUse: "Content loading states — list placeholders, card skeletons, profile loading.",
    whenNotToUse: "Full-page loading (use loading-spinner instead), or final rendered content.",
    filesAdded: ["components/ui/skeleton.tsx"],
  },
  {
    slug: "searchable-select",
    name: "Searchable Select",
    tagline: "Modal searchable picker with type-to-filter, label display, and multi-select support.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install searchable-select",
    features: [
      "Search-as-you-type filtering",
      "Modal bottom-sheet style interface",
      "Multi-select mode with tag display",
      "Label and placeholder support",
      "Selected value display in trigger",
    ],
    whenToUse: "Country pickers, category selectors, tag inputs, any large option list needing search.",
    whenNotToUse: "2-5 option lists (use custom-radio instead), or static selection.",
    filesAdded: ["components/ui/searchable-select.tsx"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    tagline: "Countdown timer displaying days, hours, minutes, and seconds with colon-separated format.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install countdown-timer",
    features: [
      "Auto-decrementing timer with 1-second intervals",
      "Days, hours, minutes, seconds display",
      "Flash sale urgency styling",
      "onComplete callback when timer hits zero",
    ],
    whenToUse: "Flash sales, limited-time offers, event countdowns, OTP expiration timers.",
    whenNotToUse: "Precise time tracking (use a proper date library for accuracy).",
    filesAdded: ["components/ui/countdown-timer.tsx"],
  },
  {
    slug: "otp-input",
    name: "OTP Input",
    tagline: "One-time password input with individual digit boxes, auto-advance, and paste support.",
    category: "ui",
    categoryLabel: "UI",
    install: "npx vibekit-native install otp-input",
    features: [
      "Individual digit input boxes (default 6 digits)",
      "Auto-advance to next field on entry",
      "Auto-backspace to previous field",
      "Paste support for OTP codes",
      "Configurable digit count",
    ],
    whenToUse: "OTP verification screens, 2FA codes, phone verification, magic link code entry.",
    whenNotToUse: "Regular text or password input (use the Input component instead).",
    filesAdded: ["components/ui/otp-input.tsx"],
  },

  // ─── Commerce ──────────────────────────────
  {
    slug: "product-card",
    name: "Product Card",
    tagline: "Product card with optimized image, price, rating, badge overlay, and wishlist/add-to-cart actions.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install product-card",
    prerequisites: ["Expo project with expo-image"],
    features: [
      "Optimized product image with expo-image",
      "Price display with discount badge",
      "Rating stars with review count",
      "Wishlist toggle and add-to-cart actions",
      "Color variant dots below image",
    ],
    whenToUse: "Product listing grids, catalog screens, search results, wishlist display.",
    whenNotToUse: "Cart items (use cart-item component), or product detail (use product-header).",
    filesAdded: ["components/commerce/product-card.tsx"],
  },
  {
    slug: "cart-item",
    name: "Cart Item",
    tagline: "Cart line item with image, title, quantity stepper, unit price, total, and remove action.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install cart-item",
    features: [
      "Product thumbnail image",
      "Title, variant info, and unit price",
      "Quantity increment/decrement stepper",
      "Line total calculation",
      "Remove action with trash icon",
    ],
    whenToUse: "Shopping cart screens, order review before checkout, wishlist-to-cart transfer.",
    whenNotToUse: "Non-editable order summary (use order-card instead).",
    filesAdded: ["components/commerce/cart-item.tsx"],
  },
  {
    slug: "price-display",
    name: "Price Display",
    tagline: "Price display with currency formatting, compare-at strikethrough, discount percentage badge, and configurable size.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install price-display",
    features: [
      "Formatted price with configurable currency",
      "Compare-at price with strikethrough",
      "Discount percentage badge",
      "Size variants: sm, md, lg",
    ],
    whenToUse: "Product prices anywhere — cards, detail pages, cart, order summaries.",
    whenNotToUse: "Non-commerce numeric display (use plain Text with formatting).",
    filesAdded: ["components/commerce/price-display.tsx"],
  },
  {
    slug: "order-card",
    name: "Order Card",
    tagline: "Order summary card with ID, date, status badge, item previews, total, and reorder action.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install order-card",
    features: [
      "Order ID, date, and status badge",
      "Item thumbnail previews with count",
      "Order total display",
      "Reorder action button",
    ],
    whenToUse: "Order history lists, my-orders screens, account order management.",
    whenNotToUse: "Live cart items (use cart-item component).",
    filesAdded: ["components/commerce/order-card.tsx"],
  },
  {
    slug: "order-timeline",
    name: "Order Timeline",
    tagline: "Vertical timeline showing order status progression with icons, dates, and completion states.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install order-timeline",
    features: [
      "Step-by-step vertical timeline",
      "Completed, active, and pending states with color coding",
      "Date and time per step",
      "Icon per step via Ionicons",
      "Connecting lines between steps",
    ],
    whenToUse: "Order tracking, delivery status, shipment progress, onboarding wizard steps.",
    whenNotToUse: "Simple status label (use badge component instead).",
    filesAdded: ["components/commerce/order-timeline.tsx"],
  },
  {
    slug: "product-header",
    name: "Product Header (Detail)",
    tagline: "Full product detail header with image gallery, color/size selector, wishlist, and sticky add-to-cart.",
    category: "commerce",
    categoryLabel: "Commerce",
    install: "npx vibekit-native install product-header",
    registryDependencies: ["badge", "rating", "divider"],
    prerequisites: ["Expo project with expo-image"],
    features: [
      "Horizontal image gallery with dots indicator",
      "Color variant selector (circular swatches)",
      "Size selector (pill buttons)",
      "Rating and review count display",
      "Wishlist toggle with heart icon",
      "Sticky bottom add-to-cart bar with price",
      "Description section with read-more",
    ],
    whenToUse: "Product detail screens, PDP (product detail page) in e-commerce apps.",
    whenNotToUse: "Product list cards (use product-card component).",
    filesAdded: ["components/commerce/product-header.tsx"],
  },

  // ─── Auth ───────────────────────────────────
  {
    slug: "login-screen",
    name: "Login Screen",
    tagline: "Login screen with email/password form, validation (zod + react-hook-form), social buttons, and navigation links.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install login-screen",
    prerequisites: ["Expo Router", "react-hook-form", "zod", "@hookform/resolvers"],
    features: [
      "Email + password form with zod validation",
      "Password visibility toggle",
      "Social login buttons (Google, Apple, Facebook)",
      "Forgot password and sign-up navigation links",
      "Safe-area-aware layout with KeyboardAvoidingView",
      "useSafeAreaInsets integration",
    ],
    whenToUse: "Email/password authentication screens, login-as-first-screen apps.",
    whenNotToUse: "OTP-only login (use verify-otp-screen), or OAuth-only flows.",
    filesAdded: ["components/auth/login-screen.tsx"],
  },
  {
    slug: "register-screen",
    name: "Register Screen",
    tagline: "Registration screen with name, email, password fields, zod validation, and social sign-up options.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install register-screen",
    prerequisites: ["Expo Router", "react-hook-form", "zod", "@hookform/resolvers"],
    features: [
      "Full name, email, password, confirm password fields",
      "zod schema validation with password strength rules",
      "Password visibility toggles",
      "Social sign-up buttons",
      "Login navigation link",
      "Safe-area-aware with KeyboardAvoidingView",
    ],
    whenToUse: "User registration, sign-up flows, account creation screens.",
    whenNotToUse: "Admin user creation (use a form with additional role fields).",
    filesAdded: ["components/auth/register-screen.tsx"],
  },
  {
    slug: "verify-otp-screen",
    name: "Verify OTP Screen",
    tagline: "OTP verification screen with 6-digit code input, resend timer, and email display.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install verify-otp-screen",
    registryDependencies: ["otp-input"],
    features: [
      "6-digit OTP input with auto-advance",
      "Masked email display showing destination",
      "Resend code button with countdown timer",
      "Auto-submit on complete entry",
    ],
    whenToUse: "Email verification, phone verification, 2FA code entry, password reset confirmation.",
    whenNotToUse: "Password-based login (use login-screen instead).",
    filesAdded: ["components/auth/verify-otp-screen.tsx"],
  },
  {
    slug: "forgot-password-screen",
    name: "Forgot Password Screen",
    tagline: "Forgot password screen with email input, validation, and submit action for reset link.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install forgot-password-screen",
    prerequisites: ["react-hook-form", "zod", "@hookform/resolvers"],
    features: [
      "Email input with zod validation",
      "Submit button with loading state",
      "Back to login link",
      "Success message display after submission",
    ],
    whenToUse: "Password reset initiation, forgot password flow start.",
    whenNotToUse: "Direct password reset (use new-password-screen after OTP verification).",
    filesAdded: ["components/auth/forgot-password-screen.tsx"],
  },
  {
    slug: "new-password-screen",
    name: "New Password Screen",
    tagline: "New password creation screen with strength validation, confirm password, and submit.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install new-password-screen",
    prerequisites: ["react-hook-form", "zod", "@hookform/resolvers"],
    features: [
      "New password + confirm password fields",
      "Password strength validation (min length, uppercase, number)",
      "Password visibility toggles",
      "Loading state on submit",
    ],
    whenToUse: "Password reset completion, first-time password setup, change password forms.",
    whenNotToUse: "Login flow (use login-screen), or registration (use register-screen).",
    filesAdded: ["components/auth/new-password-screen.tsx"],
  },
  {
    slug: "complete-profile-screen",
    name: "Complete Profile Screen",
    tagline: "Post-registration profile completion with avatar upload, username, phone, and date of birth fields.",
    category: "auth",
    categoryLabel: "Auth",
    install: "npx vibekit-native install complete-profile-screen",
    registryDependencies: ["input", "custom-radio"],
    prerequisites: ["react-hook-form", "zod", "@hookform/resolvers", "expo-image-picker"],
    features: [
      "Avatar picker with expo-image-picker",
      "Username, phone, date of birth fields",
      "Gender radio selection",
      "zod validation for all fields",
      "Save button with loading state",
    ],
    whenToUse: "Onboarding profile completion, first-time user profile setup.",
    whenNotToUse: "Simple name-only updates (use a minimal form instead).",
    filesAdded: ["components/auth/complete-profile-screen.tsx"],
  },

  // ─── Home ───────────────────────────────────
  {
    slug: "hero-banner",
    name: "Hero Banner",
    tagline: "Full-width hero banner with autoplay carousel, gradient overlays, action buttons, and dot indicators.",
    category: "home",
    categoryLabel: "Home",
    install: "npx vibekit-native install hero-banner",
    features: [
      "Autoplay carousel with configurable interval",
      "Gradient overlay on images for text readability",
      "Title, subtitle, and CTA button per slide",
      "Dot indicators for current slide position",
      "Swipe gesture navigation",
    ],
    whenToUse: "Home page hero sliders, promotional banners, featured content carousels.",
    whenNotToUse: "Static image banners (use a simple Image component instead).",
    filesAdded: ["components/home/hero-banner.tsx"],
  },
  {
    slug: "section-header",
    name: "Section Header",
    tagline: "Section header with title, optional subtitle, and see-all action link.",
    category: "home",
    categoryLabel: "Home",
    install: "npx vibekit-native install section-header",
    features: [
      "Bold section title with optional subtitle",
      "See-all / view-all action link on the right",
      "Consistent padding and typography",
    ],
    whenToUse: "Home page section headings — featured products, categories, recommended items.",
    whenNotToUse: "Page-level headings (use your navigation header instead).",
    filesAdded: ["components/home/section-header.tsx"],
  },
  {
    slug: "category-circles",
    name: "Category Circles",
    tagline: "Horizontal scrollable row of circular category icons with labels.",
    category: "home",
    categoryLabel: "Home",
    install: "npx vibekit-native install category-circles",
    features: [
      "Horizontal ScrollView with circular pressable items",
      "Category icon and label per item",
      "Visible overflow for scroll hint",
    ],
    whenToUse: "Category navigation on home pages, browse-by-category sections.",
    whenNotToUse: "Filter chips (use filter chips in a horizontal bar instead).",
    filesAdded: ["components/home/category-circles.tsx"],
  },
  {
    slug: "flash-sale-timer",
    name: "Flash Sale Timer",
    tagline: "Flash sale section header with live countdown timer and product preview strip.",
    category: "home",
    categoryLabel: "Home",
    install: "npx vibekit-native install flash-sale-timer",
    registryDependencies: ["countdown-timer"],
    features: [
      "Flash sale label with urgency styling",
      "Live countdown timer (HH:MM:SS)",
      "Horizontal product preview strip below",
    ],
    whenToUse: "Flash sale or limited-time offer sections on home pages and promotions.",
    whenNotToUse: "Regular product listings (use product-card in a grid instead).",
    filesAdded: ["components/home/flash-sale-timer.tsx"],
  },

  // ─── Shared ─────────────────────────────────
  {
    slug: "screen-header",
    name: "Screen Header",
    tagline: "App screen header with back button, title, and optional right action buttons.",
    category: "shared",
    categoryLabel: "Shared",
    install: "npx vibekit-native install screen-header",
    features: [
      "Back button with safe-area top inset",
      "Centered title text",
      "Left and right action button slots",
      "Consistent dark styling",
    ],
    whenToUse: "Every app screen that needs a header with back navigation and optional actions.",
    whenNotToUse: "Tab screens without back navigation (hide back button).",
    filesAdded: ["components/shared/screen-header.tsx"],
  },
  {
    slug: "filter-sheet",
    name: "Filter Sheet",
    tagline: "Bottom sheet filter panel with multi-select options, clear all, and apply actions.",
    category: "shared",
    categoryLabel: "Shared",
    install: "npx vibekit-native install filter-sheet",
    features: [
      "Bottom sheet presentation with drag handle",
      "Multi-select filter sections",
      "Clear all and Apply action buttons",
      "Active filter count display",
    ],
    whenToUse: "Product listing filters, search refinement, settings option lists.",
    whenNotToUse: "Simple sort selection (use filter-sort-bar for sort-only).",
    filesAdded: ["components/shared/filter-sheet.tsx"],
  },
  {
    slug: "filter-sort-bar",
    name: "Filter & Sort Bar",
    tagline: "Horizontal toolbar with filter and sort buttons, active filter count badge, and modal pickers.",
    category: "shared",
    categoryLabel: "Shared",
    install: "npx vibekit-native install filter-sort-bar",
    features: [
      "Filter button with active filter count badge",
      "Sort button with option picker modal",
      "Horizontal layout with consistent spacing",
    ],
    whenToUse: "Product listing toolbars, search result sort/filter controls.",
    whenNotToUse: "Detailed filter panels (use filter-sheet instead).",
    filesAdded: ["components/shared/filter-sort-bar.tsx"],
  },
  {
    slug: "search-bar",
    name: "Search Bar",
    tagline: "Rounded search input with clear button, optional camera/scanner icon, and submit handler.",
    category: "shared",
    categoryLabel: "Shared",
    install: "npx vibekit-native install search-bar",
    features: [
      "Pill-shaped search input with leading search icon",
      "Clear text button when input is non-empty",
      "Optional camera/scanner icon on the right",
      "onSubmitEditing for search execution",
    ],
    whenToUse: "Search headers, product search, filter-by-keyword inputs.",
    whenNotToUse: "Form text inputs (use the Input component instead).",
    filesAdded: ["components/shared/search-bar.tsx"],
  },

  // ─── Chat ───────────────────────────────────
  {
    slug: "chat-bubble",
    name: "Chat Bubble",
    tagline: "Chat message bubble with own/other alignment, text, time, and read status.",
    category: "chat",
    categoryLabel: "Chat",
    install: "npx vibekit-native install chat-bubble",
    features: [
      "Own message (right-aligned, accent color) and other (left-aligned, dark)",
      "Bubble with sharp corners on one side",
      "Timestamp display below each bubble",
      "Read/delivered status indicator (checkmarks)",
    ],
    whenToUse: "In-app chat, direct messaging, customer support conversations.",
    whenNotToUse: "Comments or reviews (use a flat list with comment layout instead).",
    filesAdded: ["components/chat/chat-bubble.tsx"],
  },
  {
    slug: "chat-input",
    name: "Chat Input",
    tagline: "Multiline message composer with attach + send and KeyboardAvoidingView.",
    category: "chat",
    categoryLabel: "Chat",
    install: "npx vibekit-native install chat-input",
    features: [
      "Auto-growing multiline input with min/max height",
      "Attach button (configurable handler)",
      "Send button activates only on non-empty input",
      "Keyboard-aware on iOS via KeyboardAvoidingView",
      "Respects safe-area bottom inset",
    ],
    whenToUse: "Bottom of any chat screen — pair with chat-list and chat-bubble.",
    whenNotToUse: "Single-line search or comment forms (use input instead).",
    filesAdded: ["components/chat/chat-input.tsx"],
  },
  {
    slug: "chat-list",
    name: "Chat List",
    tagline: "Inverted FlatList of messages with pull-to-refresh and pagination.",
    category: "chat",
    categoryLabel: "Chat",
    install: "npx vibekit-native install chat-list",
    features: [
      "Inverted FlatList for native chat scrolling behaviour",
      "Pull-to-refresh and onEndReached pagination",
      "Empty state placeholder",
      "Renders chat-bubble for each message",
    ],
    whenToUse: "Main conversation surface in any messaging or AI-chat screen.",
    whenNotToUse: "Static lists or feed UIs (use a normal FlatList).",
    filesAdded: ["components/chat/chat-list.tsx"],
  },
  {
    slug: "chat-header",
    name: "Chat Header",
    tagline: "Conversation header with avatar, online status, and call/video/more actions.",
    category: "chat",
    categoryLabel: "Chat",
    install: "npx vibekit-native install chat-header",
    features: [
      "Avatar + name + online/typing/last-seen status",
      "Back, voice-call, video-call, and more buttons (all optional)",
      "Safe-area top inset + bottom border",
    ],
    whenToUse: "Top of any direct-message or group-chat screen.",
    whenNotToUse: "Standalone screens (use screen-header instead).",
    filesAdded: ["components/chat/chat-header.tsx"],
  },

  // ─── Profile ────────────────────────────────
  {
    slug: "points-card",
    name: "Points Card (Loyalty)",
    tagline: "Loyalty points card with balance, tier progress bar, tier name, and history action.",
    category: "profile",
    categoryLabel: "Profile",
    install: "npx vibekit-native install points-card",
    features: [
      "Large points balance display",
      "Tier name and progress bar to next tier",
      "Current tier badge",
      "Points history action button",
    ],
    whenToUse: "Loyalty program screens, rewards dashboards, profile points summary.",
    whenNotToUse: "Simple numeric display (use Text component instead).",
    filesAdded: ["components/profile/points-card.tsx"],
  },
  {
    slug: "coupon-card",
    name: "Coupon / Voucher Card",
    tagline: "Discount coupon card with left accent bar, code, description, expiry, and apply action.",
    category: "profile",
    categoryLabel: "Profile",
    install: "npx vibekit-native install coupon-card",
    features: [
      "Colored left accent bar (red/green/blue per type)",
      "Coupon code in monospace font",
      "Description and expiry date",
      "Apply / use-now action button",
    ],
    whenToUse: "My vouchers page, coupon listing, offer code display.",
    whenNotToUse: "Promotional banners (use a card with full-width styling instead).",
    filesAdded: ["components/profile/coupon-card.tsx"],
  },
];

export const categories: { value: ComponentCategory | "all"; label: string }[] = [
  { value: "all", label: "All" },
  { value: "ui", label: "UI" },
  { value: "commerce", label: "Commerce" },
  { value: "auth", label: "Auth" },
  { value: "home", label: "Home" },
  { value: "shared", label: "Shared" },
  { value: "chat", label: "Chat" },
  { value: "profile", label: "Profile" },
  { value: "hero", label: "Hero" },
  { value: "marketing", label: "Marketing" },
  { value: "data", label: "Data" },
  { value: "forms", label: "Forms" },
  { value: "content", label: "Content" },
  { value: "api", label: "API" },
  { value: "files", label: "Files" },
  { value: "saas", label: "SaaS" },
];

export function getComponentBySlug(slug: string): JBComponent | undefined {
  return components.find((c) => c.slug === slug);
}

export function getAllComponentSlugs(): string[] {
  return components.map((c) => c.slug);
}
